title: StyglasDK
description: Videnbase uden BS.
url: "https://styglas.dk"
baseurl: ""
lang: da

theme: just-the-docs
color_scheme: light
search_enabled: true
heading_anchors: true
back_to_top: true
back_to_top_text: "Tilbage til toppen"
footer_content: ""

compress_html:
  clippings: all
  comments: all
  endings: all

exclude:
  - "*.gem"
  - "*.gemspec"
  - Gemfile.lock
  - vendor/
  - .bundle/
